audbackend/core/backend.py

There are some occasions I haven't completely figured out yet that can lead to:
```
RuntimeError: 404 page not found
```
when calling
```python
audfactory.path(path).exists()
```
So I introduced a `try`-`except` statement that handles this case.

Fix audbackend.Artifactory.exists()

---

audbackend/core/backend.py
tests/test_backend.py

I realized we were not supporting the case that the file extension is empty. Now the following works, too:
```python
backend = audbackend.create('file-system', 'host', '/host')
backend.path('my.file.without.ext', '1.0.0', ext='')
```
```
/host/my.file.without.ext/1.0.0/my.file.without.ext-1.0.0
```

Support empty file extension

---

docs/authentication.rst

This changes the authentication documentation by providing a link to the `audfactory` documentation as single source of truth.

DOC: link to audfactory for authentication

---

audbackend/__init__.py
audbackend/core/repository.py
docs/api.rst

This adds the `audbackend.Repository` class, which we can then easily reuse in every project that needs to address repositories.
The users there don't have to call the actual `audbackend` package, but we could directly import in the `__ini__.py` file. E.g. for `audb` it would be
```python
from audbackend import Repository
```
instead of
```python
from audb.core.repository import Repository
```

Add audbackend.Repository

---

audbackend/core/backend.py
tests/test_backend.py

Closes #22
Fixes the problem and adds a test for it.
```python
backend = audbackend.create('artifactory', 'http://host', 'repository')
backend.join('', '', 'file.txt')
```
```
file.txt
```

FIX: ignore empty strings in backend.join()

---

audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/filesystem.py
tests/test_backend.py

This adds `audbackend.Backend.ls()` as a method to show the content of a folder on the backend.
The idea is to provide a solution so a user have not to use `glob()` to find files in a repo.
I tested it in `audb` to make `audb.available()` faster (see https://github.com/audeering/audb/pull/131):
* Execution time using `glob()`: 237s
* Execution time using `ls()`: 100s

Add audbackend.Backend.ls()

---

audbackend/core/artifactory.py
setup.cfg
tests/test_backend.py

Closes #26 
When accessing a non-existing path or a path where you don't have the permission to access it, you might experience a 403 error returned from Artifactory. This started happening only since a few days and most likely it depends on the version of `dohq-artifactory` and maybe if you have anonymous access enabled or not.
Here, we don't care, but just catch the corresponding error in order to return a proper `False` for `exists()` and an empty list for `glob()`.

Catch 403 Error for Artifactory backend paths

---

audbackend/core/backend.py
audbackend/core/utils.py
tests/test_backend.py

We check that a given path name includes only allowed chars.
But for `audbackend.Backend.put_archive()` we did first create the archive and only afterwards checked for the correct path name.
This has two disadvantages:
* it can take some time before the error is raised as the archive is first created
* on Windows it might fail before as it cannot create the archive locally, compare https://github.com/audeering/audb/runs/5320867038?check_suite_focus=true
I added a test for using a non-supported archive name, which fails for the `master` under Widnows with an `OSError`, see https://github.com/audeering/audbackend/runs/5321158317?check_suite_focus=true
I then added the check for the correct name at the beginning of `put_archive()`, which now raises our custom `ValueError`.

Check for path name before creating archive

---

setup.cfg

Closes #34.
As we introduced support for Python 3.9 in `audfactory` v1.0.8, I think it does not harm to request that version here as we want to support Python 3.9 here as well.

Depend on audfactory>=1.0.8

---

audbackend/core/backend.py

`Backend._get_file()` does not return a value.

Fix return value type hint of Backend._get_file()

---

audbackend/core/artifactory.py
tests/test_backend.py

Closes #51  
Fixed by not relying on `audfactory.url()` to create url as it converts `.` to `/`.
`audfactory.url()` is still used in `Artfactory.ls()` and `Artifactory.glob()`, but these functions will be changed / removed anyway, see #46

Properly handle dots in backend folder on Artifactory

---

audbackend/__init__.py
audbackend/core/api.py
audbackend/core/backend.py
audbackend/core/conftest.py
docs/api.rst

Closes #55 
Note that `Backend.__repr__()` is now implemented to have a nicer representation of the backend objects. The docstring example of `Backend.create()` has been improved accordingly.

Add available() to list available backends

---

audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/filesystem.py
tests/conftest.py
tests/test_backend.py

Relates to #46 
Closes https://github.com/audeering/audbackend/issues/10 #25  #37 https://github.com/audeering/audbackend/issues/48 #49
This re-implements `Backend.ls()` by not returning the path on the backend, but a list of virtual paths together with version and extension, so we can close #10 and #25 
In the test we now create three files that have the same virtual path, but we set a different extension. If a backend does not translate it into three different paths, the test will fail, so we can close #49 
We now raise a `FileNotFoundError` error  folder does not exist, so we can close #37

Reimplement Backend.ls()

---

.github/workflows/flake8.yml
.pre-commit-config.yaml
CONTRIBUTING.rst
setup.cfg
tests/conftest.py
tests/requirements.txt

This uses [pre-commit](https://pre-commit.com) instead of `pytest` to execute the `flake8` tests.
It also fixes a few flake8 issues and adds a coding convention section to CONTRIBUTING.

TST: use pre-commit for flake8 checks

---

audbackend/core/artifactory.py
setup.cfg
tests/conftest.py
tests/test_artifactory.py

Closes #72 
`dohq-artifactory` changed the returned error for a non-existing path/HTTP request error to `artifactory.exception.ArtifactoryException`, whcih means we need to update `audbackend.core.artifactory._non_existing_path_error` to catch that error as well.
I added two tests for it by providing wrong Artifactory credentials, which both fail with
```
dohq_artifactory.exception.ArtifactoryException
```
if the proposed changes to the code are not included.

Fix: support artifactory.exception.ArtifactoryException

---

audbackend/core/backend.py

Something we overlooked in https://github.com/audeering/audbackend/pull/62:
The return type of `audbackend.Backend.ls()` needs to be updated as it no longer returns the file extension, but only name and version.

DOC: fix return type of Backend.ls()

---

audbackend/core/backend.py
audbackend/core/conftest.py
tests/test_backend.py

Closes #78 
The methods `Backend.put_archive()` and `Backend.get_archive()` do no longer extend the archive name with `.zip`. Instead the user has to provide the extension. In addition to ZIP, also TAR.GZ is now supported.

Force archive extension and add support for TAR.GZ

---

audbackend/core/backend.py
tests/test_backend.py

This documents `PermissionError` for `Backend.get_archive()` and `Backend.get_file()` if the user has no local write permissions.
In addition, it adds tests for all errors we currently have documented in `audbackend.Backend` methods,
and fixes a few typos in the docstrings.

TST: test for all Backend errors

---

audbackend/core/api.py
audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/conftest.py
audbackend/core/filesystem.py
audbackend/core/utils.py
tests/conftest.py
tests/test_artifactory.py
tests/test_backend.py

Relates to #89, https://github.com/audeering/audbackend/issues/86, #24 
When a backend is created it will create the repository if it does not exist. This may raise a `BackendError` and the docstring has been extended accordingly:
Other changes:
* It is no longer possible to use a folder inside an Artifactory repository as repository
* To avoid a BackendError is now raised in the docstring examples, the Artifactory backend has been removed. 
* The docstring examples have been further simplified by directly setting the working directory to the temporary folder.
* The test for listing an empty repository is re-enabled.

Create repository if it does not exist

---

audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/filesystem.py
audbackend/core/utils.py
tests/test_artifactory.py
tests/test_backend.py

Closes https://github.com/audeering/audbackend/issues/61
This adds the argument `suppress_backend_errors` to the following functions:
`Backend._ls()` and `Backend._versions()` are now supposed to raise an error if the `path` does not exist.

Suppress backend errors

---

audbackend/__init__.py
audbackend/core/api.py
audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/filesystem.py
docs/api-src/audbackend.rst
tests/conftest.py
tests/test_api.py
tests/test_artifactory.py
tests/test_backend.py

Closes #92 
This adds `audbackend.delete()` as counterpart to `audbackend.create()`, i.e. it deletes the respository and removes the instance from the available backend instances. Since it is not directly available as function of `Backend` it avoids the problem that a user does, e.g.:
```
backend = audbackend.create(...)
backend.delete()
backend.ls()  # would fail since repository was deleted
```
Other changes:
* The docstring of `audbackend.available()` and `audbackend.create()` are slightly improved
* All function so the API are not tested in `tests/test_api.py`
* The fixture that generates the backend objects is moved to `tests/conftest.py` and shared by all test files

Add audbackend.delete()

---

setup.cfg

In https://github.com/audeering/audbackend/pull/96 we introduced to use `audeer.list_dir_names(..., hidden=True)` which requires `audeer` >=1.19.0.

Require audeer>=1.19.0

---

tests/conftest.py

Closes #97 
This introduces two steps to try to remove repositories on Artifactory
* It tries up to 3 times to remove the repo and catches `BackendErrors` in the `backend()` fixture. After that it raises a `RuntimeError` and asks the user to manually delete the repo.
* In addition, it adds a session UID to the repo name, so it is easier to recognize remaining repositories on the host

TST: add cleanup of leftover Artifactory repos

---

tests/conftest.py
tests/test_api.py

This removes creating the file-system host in the current folder, but use a pytest temp folder instead.

TST: let pytest handle tmp dirs

---

tests/conftest.py

Seeing
I realized that we forgot `''` in the suggested command, which is fixed in this pull request.

TST: correcting suggested repo cleanup command

---

audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/filesystem.py

In `put_file()` we calculate the checksum to determine if the same file already exists on the backend. If the check fails, we can pass the checksum on to the backend to avoid it is calculated again or differently.

put_file(): pass checksum to implementation

---

setup.cfg
tests/test_backend.py

With `audeer>=1.20.0` we can now rely on `audeer.md5` and use `files=None` with `audeer.create_archive()`.

Update to audeer>=1.20.0

---

audbackend/__init__.py
audbackend/core/backend.py
audbackend/core/filesystem.py
audbackend/core/utils.py
docs/api-src/audbackend.rst
tests/test_backend.py

This removes `audbackend.md5`. 
Usually we would probably deprecate it first, but since we have so many breaking changes, I guess it's fine to remove it.

Calculate md5 with audeer

---

audbackend/core/backend.py
audbackend/core/utils.py
tests/test_backend.py

Closes #https://github.com/audeering/audbackend/issues/101
* Checks that version matches `[A-Za-z0-9._-]+`
* Hard codes backend separator (`/`) in `utils.py` (otherwise we cannot compile the regex expression)
* More verbose error message

Check version argument

---

audbackend/core/backend.py

Adds to the docstring when a folder is created:

DOC: document when folder is created

---

audbackend/core/backend.py
tests/test_backend.py

Insert missing `NotADirectoryError` in raises section of `Backend.put_archive()` and adds a test for it. Also adds the same test for `Backend.get_archive()`.

put_archive(): raise NotADirectoryError

---

audbackend/core/artifactory.py
tests/test_artifactory.py
tests/test_backend.py

Closes #76 #129 
With this PR we add support for storing files on Artifactory using the old structure, i.e.:
`<host>/<repository>/<folder>/<name-wo-ext>/<version>/<name-wo-ext>-<version>.<ext>`
In packages where we want to stick with the old structure we can then do:
```python
backend = audbackend.access(...)
if isinstance(backend, audbackend.Artifactory):
backend._use_legacy_file_structure(extensions=...)
```
Other changes:
* Checks if config file exists before trying to read credentials from it

Artifactory: support old file structure

---

docs/requirements.txt

The Python kernel seems to be no longer a requirement when installing `jupyter-sphinx`, so we have to add it manually to the dependencies.

CI: add ipykernel to requirements

---

audbackend/core/filesystem.py
tests/test_filesystem.py

Closes https://github.com/audeering/audbackend/issues/136
Analogous to https://github.com/audeering/audbackend/pull/130 this adds `FileSystem._use_legacy_file_structure()` to support our legacy file systems on existing repositories.
Default:
```python
import tempfile
import audbackend
import audeer
with tempfile.TemporaryDirectory(dir='.') as host:
backend = audbackend.create('file-system', host, 'repo')
file = audeer.touch('file')
backend.put_file(file, '/sub/file.txt', '1.0.0')
backend.put_file(file, '/sub/file.tar.gz', '1.0.0')
files = audeer.list_file_names(host, recursive=True, basenames=True)
print(files)
```
```
['repo/sub/1.0.0/file.tar.gz', 'repo/sub/1.0.0/file.txt']
```
Legacy:
```python
import tempfile
import audbackend
import audeer
with tempfile.TemporaryDirectory(dir='.') as …
```

FileSystem: support old file structure

---

audbackend/__init__.py

`pkg_resources` is deprecated and since Python 3.8 we can use `importlib.metadata` to get the version of a package.

Use importlib.metadata instead of pkg_resources

---

docs/index.rst
docs/legacy.rst

Closes #131 
This adds a new entry to the documentation how to continue using the old file structure on file-system and artifactory backends.

DOC: discuss legacy backends

---

tests/conftest.py

Replaces hard-coded user name with name of authenticated user in owner fixture.

TST: use name of authenticated user in owner fixture

---

audbackend/core/artifactory.py
audbackend/core/backend.py
audbackend/core/conftest.py
audbackend/core/filesystem.py
docs/legacy.rst
docs/usage.rst
tests/singlefolder.py
tests/test_artifactory.py
tests/test_filesystem.py

Relates to #155 
This removes the `version` argument from the backend implementation.
Instead of forwarding `path` and `version` to the implementation, `Backend` integrates the version into the path now. This simplifies the implementation of a backend, since a developer does not have to care about storing the version (especially the implementation of `_ls()` becomes way simpler). Also the support for legacy file structure is now handled directly by `Backend` (and as a side-effect supported by any backend).
The suggested changes will allow us to implement `audbackend` in a way that it can be used without versioning as requested in #155 (not implemented here).

Remove version from implementation

---

audbackend/core/api.py

DOC: use repository over backend object in all api functions

---

.github/workflows/doc.yml
README.rst
docs/api-src/audbackend.backend.rst
docs/api-src/audbackend.interface.rst
docs/api-src/audbackend.rst
docs/developer-guide.rst
docs/index.rst
docs/legacy.rst
docs/usage.rst

Closes #169 
This splits the "Usage" documentation into "Usage" and "Developer guide".
<details><summary>Usage</summary>
</details>
<details><summary>Developer guide</summary>
</details>
It also updates the landing page, and does no longer list the class names:
---
When writing the usage documentation the following things seemed slightly strange to me:
* When using `audbackend.create()` or `audbackend.access()` the backend is referred to by a string name whereas the interface needs to be given as a class. Providing it as a class makes things easier, but as a user you might be wonder why there is this difference.
* `audbackend.available()` does only list backends, not interfaces
* `audbackend.available()` can only provide information on the backend class associated with a backend name, …

DOC: split usage into usage and developer-guide

---

audbackend/core/backend/artifactory.py
audbackend/core/backend/base.py
audbackend/core/backend/filesystem.py
docs/developer-guide.rst
tests/singlefolder.py

So far the docstring of `Base._ls()` was saying:
```
If ``path`` is ``'/'`` and no files exist on the repository,
an empty list should be returned
Otherwise,
if ``path`` does not exist or no files are found under ``path``,
an error should be raised.
```
This might be overlooked by a developer, so here we simplify `_ls()` by not demanding to raise an error message or treat `/` as a special case. Instead it is sufficient to return an empty list, even in the case that the path does not exist. The docstring now says:
```
If ``path`` does not exist
an empty list can be returned.
```
To avoid a breaking change, raising a file-not-found-error is now handled by `Base`, in the same way we already do it for the case that `path` is not a sub-path.

Base._ls(): may always return an empty list

---

.github/workflows/doc.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Use Python 3.10 as default version in `test.yml`, `doc.yml`, and `publish.yml` CI workflows.

CI: use Python 3.10 as default

---

tests/misc/cleanup_artifactory.py

As we use the hidden `Artifactory._authentication()` method in `tests/misc/cleanup_artifactory.py` we need to update to the new place where the backends are stored.

TST: fix Artifactory cleanup script

---

audbackend/core/backend/artifactory.py
audbackend/core/backend/base.py
audbackend/core/backend/filesystem.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py
docs/developer-guide.rst
docs/usage.rst
tests/singlefolder.py
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Relates to #177 
Adds `backend.Base.copy_file()` to copy a file on the backend. A default implementation is provided, which downloads the files to a temporary directory and afterward uploads it to the new location. The behavior can be overwritten by implementing a custom `_copy_file()` method. In case of a versioned interface, all versions of file are copied unless a specific version is selected.
...

Copy file on backend

---

audbackend/core/backend/artifactory.py
audbackend/core/backend/base.py
audbackend/core/backend/filesystem.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py
docs/developer-guide.rst
docs/usage.rst
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Closes #177 
We introduce `backend.Base.move_file()`, which moves a file on the backend to a new location. Similar to #181 a default implementation is provided, which can be overwritten when a backend provides a native way to move files.
...

Move file on backend

---

audbackend/core/artifactory.py
tests/test_artifactory.py

Closes #186 
This add support for remote and virtual Artifactory repositories besides local ones,
by using the `find_repository()` method from the `artifactory` package, see
https://github.com/devopshq/artifactory/blob/c99d9109870e0b05e58d25c83f1458bb44bf54d6/artifactory.py#L2400-L2416
This leads to a different behavior of `audbackend.Artifactory()`. When instanciating the object it no longer raises an error if no repo could be found for the given path (or when no access rights were given for that repo). This behavior was anyway not documented. When using `audbackend.access()` it still raises an error when the username, password do not work.

Support remote and virtual Artifactory repos

---

tests/requirements.txt

`doctestplus` is not compatible with `pytest==8.1.0`, see https://github.com/audeering/audbackend/pull/190#issuecomment-1976241914

TST: depend on pytest<8.1.0

---

audbackend/core/backend/base.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Closes #189 
Adds `validate` argument to the following functions:
* `copy_file()`
* `get_archive()`
* `get_file()`
* `move_file()`
* `put_archive()`
* `put_file()`
If set to `True` a final check is performed to assert that the new file has the expected checksum. If the check fails, an `InterruptedError` is raised. This comes with additional costs calculating the checksum of the original and new file. In case of `move_file()` the file is copied and only removed if the check was successful.
Here are the new docstrings of `backend.Base`:
Similar changes were made to `interface.Unversioned` and `interface.Versioned`

Introduce optional validation step

---

audbackend/core/interface/maven.py
audbackend/core/interface/versioned.py
audbackend/interface/__init__.py
docs/api-src/audbackend.interface.rst
docs/legacy.rst
tests/test_backend_artifactory.py
tests/test_backend_filesystem.py
tests/test_interface_maven.py

Closes #168 
This adds an extra interface to handle our legacy versioned file structure.
I'm still not completely convinced by the `Maven` name. If you have a better proposal, I'm open to change the name.
---
The API documentation is currently slightly broken as it uses the name `versioned` to refer to the interface, but the problem exists also for the `Versioned` and `Unversioned` API, which also uses a mix of `interface` and their actual variable names. I propose to fix this in another pull request, after this one is finished.
Excerpt from the API documentation:
---
For now I haven't added a new section to the usage documentation, but updated the "Legacy backends" page to

Add audbackend.interface.Maven

---

audbackend/core/interface/versioned.py

Closes https://github.com/audeering/audbackend/issues/196
We first to call `backend.ls()` without passing `pattern`. If this returns an empty list we raise an error. Otherwise, we know that the directory exists. Now we apply `pattern` and return a possibly empty list.

Fix Versioned.ls(file, pattern=...)

---

audbackend/core/interface/versioned.py
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Closes https://github.com/audeering/audbackend/issues/196 (might be that this does not work automatically as we do not merge into the default branch)
Makes sure, `Interface.ls(file, pattern=...)` works for `Versioned()` and `Unversioned` interfaces.

Fix audbackend.interface.Versioned.ls(file, pattern=...)

---

audbackend/__init__.py
audbackend/core/api.py
audbackend/core/conftest.py
docs/api-src/audbackend.rst
tests/test_api.py

Relates to #197 
This pull request proposes to remove `audbackend.available()` as we cannot maintain its current behavior/results with the new approach of accessing backends by instantiating them, introduced in #200.
There might be ways to preserve its original behavior, but I don't think this is worse the effort.
I also updated `audbackend/core/conftest.py` as proposed in https://github.com/audeering/audbackend/pull/200#issuecomment-2024615148.

Remove audbackend.available()

---

tests/conftest.py

As we have continously failing tests due to the failed cleanup on Artifactory, I would propose we change this to a warning.
Then we will most likely collect some folders on Artifactory, but I think you will still see it from time to time locally, and are then reminded to clean it up.

TST: raise warning for failed Artifactory cleanup

---

audbackend/core/interface/maven.py
tests/test_interface_maven.py
tests/test_interface_versioned.py

Closes #207 
This updates the tests of `audbackend.interface.Maven` and `audbackend.interface.Versioned` to include files in sub-paths that are named as the sub-path, namely `/sub/sub.ext` and `/sub/sub/sub.ext`. Those tests pass for `audbackend.interface.Versioned`, but failed for `audbackend.interface.Maven` due to #207.
`audbackend.interface.Maven.ls()` is then fixed, by removing results from the returned list of paths for a given sub-path, that contain files. This is neccessary compared to `audbackend.interface.Versioned` as `audbackend.interface.Maven` also stores files in sub-path, e.g. `/file/1.0.0/file-1.0.0.ext`.

Fix audbackend.interface.Maven.ls() on sub-path

---

audbackend/core/backend/base.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py
audbackend/core/utils.py
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Closes #206
All backend fucntions now raise a `ValueError` if a backend path ends on `'/'` with the exception of `ls()`, `split()` and `join()` as those functions support sub-paths as argument.
The *Raises*  section in the docstrings is changed to:

Raise ValueError if backend path ends with "/"

---

audbackend/core/conftest.py
audbackend/core/errors.py
audbackend/core/interface/base.py
audbackend/core/interface/maven.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py

This pull request ensures that the docstring examples of all interfaces use always the word `interface` as variable name for an interface. Before,it could have been a mixture of `versioned`, `maven`, ..., depending which methods were inherited and which not  (as first discussed in https://github.com/audeering/audbackend/pull/194).
The examples for `audbackend.interface.Unversioned` now are:

DOC: improve interface names in docstring examples

---

tests/misc/cleanup_artifactory.py

To avoid a deprecation warning when running:
```bash
$ python tests/misc/cleanup_artifactory.py
```
we use the new way of deleting repositories in `tests/misc/cleanup_artifactory.py`.

Update Artifactory cleaning script

---

audbackend/core/api.py
tests/test_api.py

Closes #211 
This deprecates `audbackend.access()`.

Deprecate audbackend.access()

---

audbackend/core/backend/artifactory.py
audbackend/core/backend/base.py
audbackend/core/errors.py
audbackend/core/interface/maven.py
audbackend/core/interface/unversioned.py
audbackend/core/interface/versioned.py
docs/developer-guide.rst
docs/legacy.rst
tests/test_backend_artifactory.py
tests/test_backend_base.py
tests/test_interface_unversioned.py
tests/test_interface_versioned.py

Closes #216 
This adds a new `opened` attribute to the backends to track if the backend is currently open or not:
In addition, every backend method that needs access to the actual backend (e.g. `sep()` does not need this), now raises a `RuntimeError` if the backend is not opened.
Example "Raises" section for the new `RuntimeError` that is raised when the backend was not opened:

Make open a backend mandatory

---

audbackend/core/repository.py
tests/test_repository.py

Deprecates `audbackend.Repository` as we have deprecated the usage of string names for backends as well.
If an application needs this feature it should be implemented by the application, see https://github.com/audeering/audb/pull/386 for an example.
Due to https://github.com/audeering/audeer/issues/145, I don't use `audeer.deprecated()` to mark the class as deprecated.

Deprecate audbackend.Repository

---

audbackend/core/backend/artifactory.py

In https://github.com/audeering/audbackend/pull/204 we introduced the backend methods `open()` and `close()` that can be used to establish a connection to a backend. Those are of course also good candidates for handling authentication, if needed by a backend, which we added for `audbackend.backend.Artifactory` in https://github.com/audeering/audbackend/pull/215.
In `audbackend.backend.Artifactory.open()` we store an `artifactory.ArtifactoryPath` object as `audbackend.backend.Artifactory._repo`, which is an opened connection to the repository. But `artifactory.ArtifactoryPath` does not provide a method to close the connection (maybe this is also not needed?).
In the corresponding documentation it is stated that the connection can also be handled by a `requests.Session`, see …

Implement Artifactory._close()

---

tests/conftest.py

This catches an error during the deletion of a repository on an Artifactory backend during tear down of the tests,
to avoid [errors like](https://github.com/audeering/audbackend/actions/runs/8985242819/job/24678823836?pr=224):

TST: catch Artifactory error during tear down

---

CHANGELOG.rst

I would like to target the release of `audbackend` 2.0.0 for Friday morning (2024-05-10).
I have renamed already the `main` branch to `1.0.x`, to be able to make bug fix releases if needed.
I further renamed `dev` to `main`, and hence selected the `main` branch as target of this pull request.
Related pull request for `audb` is prepared and approved at https://github.com/audeering/audb/pull/386.
/cc @ChristianGeng

Release 2.0.0

---

audbackend/core/interface/maven.py

In its current implementation, the execution time of `audbackend.interface.Maven.ls()` **scales with the content of the repository / sub-folder**, as it first collects all files given under root or a sub-folder, and limits the results only afterwards for the requested file.
As all versioned belonging to a file are stored in the the sub-folder `<root>/<name>/` there is no need for this. In this pull request, I use `ls()` of the underlying backend object to inspect the content of that folder and hence speed up the execution time.

Speedup audbackend.interface.Maven.ls()

---

.github/workflows/publish.yml

As can be seen at 
I forgot to update the `peaceiris/actions-gh-pages` action in https://github.com/audeering/audbackend/pull/201

CI: update publish action to Node.js 20

---

audbackend/core/backend/minio.py
tests/conftest.py

This is not based on `main`, but expands the `minio` branch.
MinIO seems not directly to support the concept of a file owner. At least if you call their `stats_object()` method and look at its attribute `owner_name` it is always empty for me.
This pull request adds a workaround, by setting the owner explicitly as a metadata entry, every time a file is uploaded or copied to the server. The owner can then be extracted with `stats_object().metadata`. I benchmarked, and the proposed changes have no affect on the execution time of `put_file()`.
---
We should ask ourselves, if we really want to have this feature or not. If we later switch to `fsspec` for backends (https://github.com/audeering/audbackend/pull/233), we will again have the problem, that `owner` is not supported, and we will most …

Add support for owner()

---

pyproject.toml

As we updated the syntax in https://github.com/audeering/audbackend/pull/239 as well, I decided to also state a `requires-python = '>=3.9'` in `pyproject.toml`, so the new version of `audbackend` can no longer be installed under Python 3.8.

By explicit about required Python version

---

CHANGELOG.rst

The fix for Python 3.12 they introduced in `dohq-artifactory` 1.0.0 had some breaking changes how path names are returned (e.g. `/` at the end of an URL was removed), so I had to adjust the code here as well (done in https://github.com/audeering/audbackend/pull/260). I then enabled support for Artifactory Python 3.12 here as well (done in https://github.com/audeering/audbackend/pull/259).

Release 2.2.2
