audeering/audbackend

- tests/requirements.txt
To avoid https://github.com/tholo/pytest-flake8/issues/87
> TST: require flake8 <5.0.0

- audbackend/core/backend.py
- tests/test_backend.py
> Set tmp folder where archives are created / extracted

- CHANGELOG.rst
> Release v0.3.16

- audbackend/core/api.py
- audbackend/core/backend.py
- audbackend/core/conftest.py
- audbackend/core/utils.py
> DOC: add docstring examples

- tests/requirements.txt
Remove `pytest-flake8` from `tests/requirements.txt`
> TST: remove pytest-flake from requirements

- CHANGELOG.rst
> Release 0.3.17

- .github/workflows/flake8.yml
- .github/workflows/test.yml
- tests/conftest.py
This makes sure the tests are executed when creating pull requests using `dev` as base branch.
> CI: enable tests on dev branch

- audbackend/core/artifactory.py
- audbackend/core/backend.py
- audbackend/core/filesystem.py
- tests/test_artifactory.py
- tests/test_backend.py
Relates to https://github.com/audeering/audbackend/issues/46
This removes `Backend.glob()`.
> Remove Backend.glob()

- audbackend/__init__.py
- audbackend/core/api.py
- audbackend/core/artifactory.py
- audbackend/core/backend.py
- audbackend/core/conftest.py
- audbackend/core/filesystem.py
- audbackend/core/utils.py
- docs/api-src/audbackend.rst
- tests/test_api.py
Closes #99 
This is complemented by:
> Split into audbackend.access() and audbackend.create()

- audbackend/core/backend.py
- tests/test_backend.py
> get_file(): skip if file with same checksum exists

- docs/authentication.rst
- docs/index.rst
> DOC: remove authentication section

- audbackend/core/backend.py
- audbackend/core/conftest.py
- tests/test_backend.py
Closes https://github.com/audeering/audbackend/issues/88
> Backend.put_archive(): make `files` an optional argument

- audbackend/core/backend.py
- audbackend/core/utils.py
- tests/test_backend.py
> get_file() and put_file(): raise IsADirectoryError

- audbackend/core/backend.py
- tests/test_filesystem.py
> get_file(): use temporary directory

- setup.cfg
- tests/misc/cleanup_artifactory.py
Cleanuning up Artifactory repos during the tests still fails from time to time and we had collected some abandoned repos on the server:
This adds a script that can be called to delete all `unittest-*` repos. I called it already one time and all remaining repos were removed:
```bash
$ python cleanup_artifactory.py 
1 /   28 Deleted unittest-038f5e78-4a9fb32a
2 /   28 Deleted unittest-04a5412a-7e58a2b4                           
3 /   28 Deleted unittest-05b19914-43f63ba2
4 /   28 Deleted unittest-05d9fe0a-7a00ea15                                 
5 /   28 Deleted unittest-1d7b0f70-723b2f58                         
6 /   28 Deleted unittest-1f546ca3-587d22df
7 /   28 Deleted unittest-26280718-70eb3f04       
8 /   28 Deleted unittest-2a636368-bde37c04
9 /   28 Deleted …
```
> TST: script to clean up Artifactory repos

- audbackend/core/artifactory.py
- audbackend/core/backend.py
- audbackend/core/filesystem.py
Corrects and adds missing return types of `Backend._ls()`.
> Backend._ls(): fix typing

- tests/conftest.py
The proposed command to cleanup Artifactory never worked for me, so I propose to update the suggested command to the cleaning script.
> TST: update suggested repo cleanup command

- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- docs/usage.rst
Closes #60
Adds a usage section to the documentation discussing:
* How to use existing backends
* How to develop new backends
> DOC: add usage section

- audbackend/core/artifactory.py
- audbackend/core/filesystem.py
- tests/test_artifactory.py
- tests/test_filesystem.py
> Add regex support to _use_legacy_file_structure()

- audbackend/core/backend.py
- tests/test_backend.py
> Backend.ls(): apply pattern to basename

- audbackend/core/backend.py
> audbackend.exists(): fix raises section

- CHANGELOG.rst
> Release 2.0.1
